version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - goimports
    - gofmt

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - copyloopvar
    - unconvert
    - gosec
    - noctx
    - gocritic
    - testifylint
    - goconst
    - nilerr
    - contextcheck
    - whitespace